### ISSUE TITLE
Export to FS DB format.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/airscore#43]
https://github.com/kuaka/airscore/blob/6456bb9d69e9a4fefd280a746bf977ffbf3e3e51/cgi-bin/fsdb.py#L3-L4

If we had export to `*.fsdb`, the XML of FS, then we could do visual comparisons to a reference implementation of GAP, https://github.com/geoffwong/airscore/issues/3#issuecomment-552128492

> The `*.fsdb` file contains inputs and outputs (the scores) as well as some other data of interest in checking the scores. If you are able to export from airscore to this FS XML format then [flare-timing](https://github.com/BlockScope/flare-timing) can be used to visually check those scores, as I've done for the [2018 XC Dalmatian Paragliding Open](http://2018-dalmatian.flaretiming.com). For that comp, if you select a task, then under the [Score] tab you'll see tables and in these the black columns show values picked up from the `*.fsdb` file and the difference to those same values as calculated by `flare-timing`, acting here as a reference implementation.

**Comment by biuti** [comment]
I create a [class](https://github.com/kuaka/airscore/blob/new_code/cgi-bin/fsdb.py) to deal with FSDB.
It was some time ago tho and a lot of things changed since I created it.

I will update in new_code branch that file, changing the import function if needed, and creating the export one.

On a side note, task JSON files created from AirScore contain almost the same infos with very similar names to FSDB, so for comparing porpoise, they could be useful meanwhile.

**Comment by biuti** [comment]
FSDB export should be fixed with commit https://github.com/kuaka/airscore/commit/abcb7f3a41367a1c1cc74681c8fb8ce1a55cb5f4

Still needs a frontend link.
From console, if comp_id is comp ID:
```
from fsdb import FSDB
f = FSDB.read(comp_id)
f.to_file()
```
creates fsdb file in results folder

**Comment by kuaka** [comment]
Trying to get this working for the front end but it seems to give an error with the comps that I have tried:

f = FSDB.read(52)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/airscore/core/fsdb.py", line 62, in read
    tree = ET.parse(fp)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1862, in lxml.etree._parseDocument
TypeError: cannot parse from 'int'


also FSDB.to_file needs a docstring. I started writing it but I am not familiar enough to write a decent one. (for example what is the filename? does it overwrite if file exists?)

**Comment by biuti** [comment]
My fault, the correct sequence is:

```
from fsdb import FSDB
f = FSDB.create(comp_id)
f.to_file()
```

**Comment by kuaka** [comment]
Still not working with comp 45 (HG worlds). latest result files attached.
[HGworlds.zip](https://github.com/kuaka/airscore/files/4699788/HGworlds.zip)

  File "core/compUtils.py", line 105, in is_ext
    ext = db.session.query(C.external).filter_by(comp_id=comp_id).one().scalar()
AttributeError: 'result' object has no attribute 'scalar'

**Comment by biuti** [comment]
Fixed with commit https://github.com/kuaka/airscore/commit/ee86cbe3e301126133d1d88bfa22754b64e2d8cc

**Comment by kuaka** [comment]
Have you tested this from start to finish?
I am still not able to make a file:
from fsdb import FSDB
f=FSDB.create(45)
f.to_file()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/airscore/core/fsdb.py", line 459, in to_file
    'penalty': 0 if not [n for n in res.notifications
  File "/app/airscore/core/fsdb.py", line 460, in <listcomp>
    if n.percentage_penalty > 0] else max(
AttributeError: 'dict' object has no attribute 'percentage_penalty'

**Comment by biuti** [comment]
Sorry I was working on a quite different branch.
Now (should be) fixed with https://github.com/kuaka/airscore/commit/26e09a553c9166e13125fcac916fce71ebfe9f1c

**Comment by kuaka** [comment]
This has been added to the front end with commit https://github.com/kuaka/airscore/commit/430478e6026ed064d323e96c4a24618f3caf9216 however the actual fsdb files need testing or verifying that they work.

**Comment by biuti** [comment]
The routine looks for the active comp result json file, so it returns None if event has not been scored yet.
In my opinion this is correct, unless we want to be able to export, for example, registered pilots list in FSDB format.
I don't think this should be a priority, but it would be possible to implement.
